config/routes.rb
Rails.application.routes.draw do
  root to: 'index#index'
  
  get '/hallinta/sivut/järjestys' => 'pages#order', as: 'admin_pages_order'
  post '/hallinta/sivut/järjestys' => 'pages#save_order', as: 'admin_pages_save_order'
  resources :pages, path: '/hallinta/sivut'
  resources :posts, path: '/hallinta/päivitykset'
  get '/hallinta' => 'admin#index', as: 'admin'
  get '/hallinta/login' => 'admin#login', as: 'admin_login'
  
  get '/päivitykset/*date' => 'posts#show'
  
  get '*text_id' => 'pages#view', as: :navigate
  

end

app/models/ckeditor/asset.rb
# class Ckeditor::Asset < ActiveRecord::Base
#   include ActiveRecord
#   include Ckeditor::Orm::ActiveRecord::AssetBase
#   include Ckeditor::Backend::Paperclip
# end

app/models/ckeditor/attachment_file.rb
# class Ckeditor::AttachmentFile < Ckeditor::Asset
#   has_attached_file :data,
#                     :url => "/ckeditor_assets/attachments/:id/:filename",
#                     :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
#
#   validates_attachment_presence :data
#   validates_attachment_size :data, :less_than => 100.megabytes
#   do_not_validate_attachment_file_type :data
#
#   def url_thumb
#     @url_thumb ||= Ckeditor::Utils.filethumb(filename)
#   end
# end

app/models/ckeditor/picture.rb
# class Ckeditor::Picture < Ckeditor::Asset
#   has_attached_file :data,
#                     :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
#                     :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
#                     :styles => { :content => '800>', :thumb => '118x100#' }
#
#   validates_attachment_presence :data
#   validates_attachment_size :data, :less_than => 2.megabytes
#   validates_attachment_content_type :data, :content_type => /\Aimage/
#
#   def url_content
#     url(:content)
#   end
# end

app/models/page.rb
class Page < ActiveRecord::Base
  validates :text_id,
    presence: true
  validates :order,
    numericality: { greater_than: 0 }
  before_validation :define_order
  # TODO: Sanitize content
  
  def self.sorted
    Page.all.sort do |a, b|
      a.order <=> b.order
    end
  end
  
  # TODO: Invalidate header cache when modifying the set of pages
  
  private
    def define_order
      if not order or order == 0
        self.order = Page.count
      end
    end
    
    def after_save
      expire_fragment 'nav'
    end
    def after_destroy; after_save; end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  
  
  attr_accessor :password_confirmation, :password
  before_save :encrypt_password
  
  validates :password_confirmation,
    presence: true,
    if: "password.present?"
  validates :password,
    confirmation: true,
    length: { minimum: 5, maximum: 72 },
    if: "password.present?"
  validates :password_hash, presence: true
  validates :password_salt, presence: true
  validates :email,
    presence: true,
    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i },
    uniqueness: { case_sensitive: false }
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def self.authenticate email, password
    user = find_by_email email
    if user
      user if user.authenticate password
    end
  end
  
  def authenticate password
    hash = BCrypt::Engine.hash_secret password, password_salt
    hash == password_hash
  end
  
  # Permission levels
  def editor?; privileges >= 0; end
  def admin?; privileges >= 1; end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  after_action :verify_authorized, :except => :index
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
  helper_method :current_user
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def user_not_authorized
    if current_user
      flash[:alert] = "Sinulla ei ole oikeutta tehdä tätä."
      redirect_to(request.referrer || root_path)
    else
      flash[:alert] = "Kirjaudu ensin sisään."
      redirect_to(request.referrer || root_path) # TODO: Redirect to login path
    end
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    authorize :index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  # For end user (uses different parameter)
  def view
    @page = Page.find_by text_id: params[:text_id]
    if @page.nil?
      render :not_found, status: :not_found
      authorize :page
    else
      authorize @page
    end
  end
  
  def show
    @page = Page.find(params[:id])
    authorize @page
    if @page.nil?
      render :not_found, status: :not_found
    end
  end
  
  def index
    @pages = Page.all
    authorize :page
  end
  
  def new
    @page = Page.new
    authorize @page
    render :edit
  end
  
  def create
    @page = Page.new(page_params)
    authorize @page
    @page.save!
    redirect_to pages_path
  end
  
  def edit
    @page = Page.find(params[:id])
    authorize @page
  end
  
  def update
    @page = Page.find(params[:id])
    authorize @page
    
    if @page.update(page_params)
      # Success
      redirect_to page_path(@page)
    else
      # Failure
      render 'edit'
    end
  end
  
  def destroy
    @page = Page.find(params[:id])
    authorize @page
    @page.destroy
    redirect_to pages_path
  end
  
  def order
    @pages_ordered = Page.sorted
    authorize :page
  end
  
  def save_order
    authorize :page
    success = true
    params[:page].each_with_index do |id, i|
      page = Page.find(id)
      page.order = i+1
      unless page.save
        success = false
      end
    end
    expire_fragment 'nav'
    render json: { :ok => success }
  end
  
  private
    
    def page_params
      params.require(:page).permit(:text_id, :title, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<% @title = "Hallintapaneeli" %>
<% @custom_layout = true %>

<div class="container">
  <h2>Sivut</h2>
  <%= link_to 'Hallitse sivuja', pages_path %>
  - <%= link_to 'Luo uusi sivu',  new_page_path %>
  - <%= link_to 'Vaihda sivujen järjestystä', admin_pages_order_path %>
</div>

<div class="container">
  <h2>Päivitykset</h2>
</div>

<% if current_user and current_user.admin? %>
  <div class="container">
    <h2>Käyttäjät</h2>
  </div>
<% end %>

app/views/index/index.html.erb
<% @title = "Etusivu" %>
<% @custom_layout = true %>
<div class="container">
  <p>Tervetuloa OKKY:n verkkosivuille.</p>
  <p>
    Olarin koti ja koulu -yhdistys edistää koulun ja vanhempien välistä
    yhteistyötä oppimisen tukena.
  </p>
</div>
<div class="container">
  <h2>Ajankohtaista</h2>
  <div class="updates">
    <div class="update">
      <h5>Kotisivujen suunnittelukilpailu</h5><hr>
      Hyvät nettisivut ovat nykyaikana menestyksen salaisuus. Hyvien nettisivujen tekemisen osaaminen on teille jokaiselle käyntikortti menestykseen...
    </div>
    <div class="update">
      <h5>Yhdistyksen vuosikokous 16.9.2015</h5><hr>
      Aika: 16.9.2015 klo 18
      Paikka: Olarin koulu, auditorio...
    </div>
    <div class="update">
      <h5>OKKY jäsenmaksut kaudelle 2015-2016</h5><hr>
      TILINUMERO: Nordea FI29 1112 3000 3318 32
      SAAJA: Olarin koulu ja koti –yhdistys ry
      JÄSENMAKSU 2015-2016: 20 euroa...
    </div>
    <div class="update">
      <h5>Hyvää ja aurinkoista kesää</h5><hr>
      Olarin koulu ja lukio on tunnettu erinomaisesta hengestään. Tervetuloa mukaan kehittämään edelleen Olarin koulun ja lukion hyvää oppimis- ja kasvuympäristöä sekä ylläpitämään mahtavaa yhteishenkeä...
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <%= image_tag('front_banner.jpg', class: 'front-banner') %>
  <%# cache('nav') do %>
    <nav>
      <%= link_to 'home', root_path, class: "material-icons mobile-exclusive mobile-menu" %>
      <!-- <a class="material-icons mobile-exclusive mobile-menu">home</a> -->
      <span class="divider mobile-exclusive"></span>
      <h1>OKKY</h1><!-- Prevent whitespace
   --><div class="items">
        <%= link_to 'home', root_path, class: 'material-icons hide-on-mobile' %>
        <% Page.sorted.each do |page| %>
          <%= link_to page.title, navigate_path(text_id: page.text_id) %>
        <% end %>
      </div>
      <span class="divider"></span>
      <%= form_tag '', class: 'search' do %>
        <%= text_field_tag :q, nil, placeholder: 'Hae...' %>
        <%= submit_tag 'search', class: 'material-icons' %>
      <% end %>
      <a href="" id="open-mobile-menu"
         class="material-icons mobile-exclusive mobile-menu"
         >menu</a>
    </nav>
  <%# end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% title_base = "OKKY" %>
  <title><%= if @title.present? then "#{title_base} - #{@title}" else title_base end %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= google_webfonts_init google: ['Signika Negative',
    'Montserrat', 'Lora', 'Material Icons'] %>
</head>
<body>

<%= render 'layouts/header', cache: true %>

<% flash.each do |name, msg| %>
  <%= content_tag :span, msg, class: "flash #{name}" %>
<% end %>

<% unless @custom_layout %>
  <div class="container">
    <%= yield %>
  </div>
<% else %>
  <%= yield %>
<% end %>

<div class="footer-divider"></div>

<footer>
  <span class="text">
    <%= link_to 'Lähdekoodi', 'https://github.com/ollpu/okky' %>
    - <%= link_to 'Hallinta', admin_path %>
  </span>
</footer>

</body>
</html>

app/views/pages/edit.html.erb
<% @title = "Muokataan sivua #{@page.title}" %>


<%
def errors_for model, field
  messages = ""
  model.errors.full_messages_for(field).each do |error|
    messages << "#{error}. "
  end
  messages
end
%>

<%= link_to 'Peruuta', request.referer || pages_path %>
<hr>
<%= form_for @page do |form| %>
  <div class="section title">
    <%= form.text_field :title, placeholder: 'Otsikko' %>
    <span class="errors"><%= errors_for @page, :title %></span>
  </div>
  <div class="section location">
    <%= form.label :text_id, 'Osoite:' %>
    /<%= form.text_field :text_id %>
    <span class="errors"><%= errors_for @page, :text_id %></span>
  </div>
  <%= form.text_area :content, style: "width: 100%; height: 16em;" %>
  
  <%= form.submit "Tallenna" %>
<% end %>

<!-- <span class="require" data-require-unload-confirmation="Oletko varma että et halua tallentaa tätä sivua?"></span> -->

app/views/pages/index.html.erb
<% @title = "Hallitse sivuja" %>

<%= link_to 'Takaisin', request.referer || pages_path %>
- <%= link_to 'Luo uusi sivu', new_page_path, data: { no_turbolink: true } %>
- <%= link_to 'Vaihda sivujen järjestystä', admin_pages_order_path %>
<hr>
<% if @pages.length >= 1 %>
  <% @pages.each do |page| %>
    <div class="page-preview">
      <%= link_to edit_page_path(page), class: 'edit', data: { no_turbolink: true } do %>
        <span class="title"><%= page.title %></span>
      <% end %>
      <span class="path"><%= "/#{page.text_id}" %></span>
      <%= link_to 'delete',
        page,
        method: :delete,
        data: { confirm: 'Haluatko varmasti poistaa tämän sivun lopullisesti?' },
        class: 'remove material-icons'
      %>
      <span class="content"><%=
        truncate sanitize(
          page.content.gsub(/<br\s*\/?>/, ' '),
          tags: [], attributes: []
        ), length: 100, separator: ' '
      %></span>
    </div>
  <% end %>
<% else %>
  Yhtään sivua ei löydetty.
<% end %>

app/views/pages/not_found.html.erb
<% @title = "Virhe 404" %>
<h2>404</h2>
<p>Pyytämääsi sivua <%= request.original_fullpath %> ei löydetty.<p>

app/views/pages/order.html.erb
<% @title = "Järjestä sivut" %>

Vedä ja järjestä sivut haluamaasi järjestykseen.
<%= form_tag admin_pages_save_order_path, class: 'page-order-form' do %>
  <ul class="page-order-container">
    <% @pages_ordered.each do |page| %>
      <li id="page_<%= page.id %>" class="page-order-dragdrop"><%= page.title %></li>
    <% end %>
  </ul>
  <%= hidden_field_tag :order, nil, class: "page-order-input" %>
  <%= submit_tag 'Tallenna' %>
<% end %>

app/views/pages/save_order.html.erb
<%= @print %>

app/views/pages/show.html.erb
<% @title = "Esikatsellaan sivua #{@page.title}" %>

<h2>Esikatsellaan sivua <%= @page.title %></h2><%# Move this to an admin bar...? %>
<%= link_to 'Takaisin', pages_path %>
 - <%= link_to 'Muokkaa tätä sivua', edit_page_path(@page) %>
<hr/>

<%= @page.content.html_safe %><%# Not sterilized! Unsafe! %>

app/views/pages/view.html.erb
<% @title = @page.title %>

<%= @page.content.html_safe %><%# Not sterilized! Unsafe! %>